services:
  - type: worker
    name: belgrade-jobs-bot
    env: python
    region: frankfurt
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    runtime: "python3"
    pythonVersion: "3.12.6"
    envVars:
      - key: TOKEN
        sync: false
      - key: SHEET_ID
        sync: false
      - key: GOOGLE_CREDS
        sync: false
